sink:
  type: proton
  addresses:
     - 127.0.0.1:8463
  cred:
    type: basic_auth
    context:
      username: default
      password:
  context:
sources:
  - name: IoT device metric
    type: metric
    enabled: false 
    settings:
      table: device_metrics
      clean_before_load: false
      concurrency: 8
      batch_size: 10000
      total_entities: 10000
      # interval is in seconds
      interval: 0
      last_run_state_db:
sources:
  - name: OpenTelemetry traces
    type: trace 
    enabled: true
    settings:
      table: otel_traces 
      clean_before_load: false
      concurrency: 8
      batch_size: 1000
      total_entities: 10000
      # interval is in seconds
      interval: 0
      last_run_state_db:

log:
  level: INFO
