sink:
  type: kafka
  addresses:
    - 10.171.90.253:9092

  cred:
    type:
    context:
      username:
      password:
  context:

sources:
  - name: IoT device metric
    type: metric
    enabled: true
    settings:
      topic: device_metrics
      num_partitions: 1
      replication_factor: 1
      clean_before_load: false
      concurrency: 8
      batch_size: 1
      total_entities: 100
      # interval is in seconds
      interval: 0
      iteration: 0
      last_run_state_db: device_locations.db

