sink:
  type: rockset
  addresses:
    - https://api.rs2.usw2.rockset.com
  cred:
    type: api_key
    context:
      key: j6OmMOWmSj6v0qWe0dNXpjCqq2Wjpqgi1qSTPiH7Xcok5zIqPMxFJsvbM4Z9Hxlu
  context:

sources:
  - name: IoT device metric
    type: metric
    enabled: true
    settings:
      table: devices
      clean_before_load: false
      concurrency: 32
      batch_size: 1000
      total_entities: 10000
      # interval is in seconds
      interval: 0
      iteration: 100000
      last_run_state_db: device_locations.db
log:
  level: INFO
