sink:
  type: clickhouse
  addresses:
     # - 123.59.211.245:9000
     - ghost:9000
  cred:
    type: basic_auth
    context:
      username: ghost
      password:
  context:
sources:
  - name: application log
    type: log
    enabled: true
    settings:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      # interval is in seconds
      interval: 2
      sample_file: ../samples/clickhouse-server.log.gz
  - name: IoT device metric
    type: metric
    enabled: true
    settings:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      total_entities: 100
      # interval is in seconds
      interval: 5
      last_run_state_db: device_locations.db
  - name: IoT device unstructure metric (pressure)
    type: unstructure_metric
    enabled: false
    settings:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      total_entities: 100
      # interval is in seconds
      interval: 1
      sourcetype: pressure
      last_run_state_db: unstructure_device_locations.db
  - name: IoT device unstructure metric (height)
    type: unstructure_metric
    enabled: false
    settings:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      total_entities: 100
      # interval is in seconds
      interval: 1
      sourcetype: height
      last_run_state_db: unstructure_device_locations.db
  - name: IoT device unstructure metric (concentration)
    type: unstructure_metric
    enabled: false
    settings:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      total_entities: 100
      # interval is in seconds
      interval: 1
      initial_base: 30
      step: 1
      max_value: 60
      duration: 30
      sourcetype: concentration
      last_run_state_db: unstructure_device_locations.db
  - name: Person data
    type: person
    enabled: true
    settings:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      total_entities: 1000000
      # interval is in seconds
      interval: 0
      last_run_state_db: person_locations.db
  - name: Crime cases
    type: crime_csv
    enabled: true
    settings:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      # injest only once
      interval: 0
      sample_file: ../samples/crime-cases.csv.gz
log:
  level: INFO
