sink:
  type: clickhouse
  addresses:
    - localhost:8463
  cred:
    type: basic_auth
    context:
      username: default
      password:
  context:

  type: rockset
  addresses:
    - https://api.rs2.usw2.rockset.com
  cred:
    type: api_key
    context:
      key: j6OmMOWmSj6v0qWe0dNXpjCqq2Wjpqgi1qSTPiH7Xcok5zIqPMxFJsvbM4Z9Hxlu
  context:

sources:
  - name: application log
    type: log
    enabled: false
    settings:
      table:
      clean_before_load: true
      concurrency: 1
      batch_size: 10000
      # interval is in seconds
      interval: 2
      sample_file: ../samples/clickhouse-server.log.gz
  - name: IoT device metric
    type: metric
    enabled: true
    settings:
      table: devices
      clean_before_load: false
      concurrency: 8
      batch_size: 10000
      total_entities: 10000
      # interval is in seconds
      interval: 0
      iteration: 100000
      last_run_state_db: device_locations.db
  - name: IoT device unstructure metric (pressure)
    type: unstructure_metric
    enabled: false
    settings:
      table:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      total_entities: 100
      # interval is in seconds
      interval: 1
      sourcetype: pressure
      last_run_state_db: unstructure_device_locations.db
  - name: IoT device unstructure metric (height)
    type: unstructure_metric
    enabled: false
    settings:
      table:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      total_entities: 100
      # interval is in seconds
      interval: 1
      sourcetype: height
      last_run_state_db: unstructure_device_locations.db
  - name: IoT device unstructure metric (concentration)
    type: unstructure_metric
    enabled: false
    settings:
      table:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      total_entities: 100
      # interval is in seconds
      interval: 1
      initial_base: 30
      step: 1
      max_value: 60
      duration: 30
      sourcetype: concentration
      last_run_state_db: unstructure_device_locations.db
  - name: Person data
    type: person
    enabled: false
    settings:
      table:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      total_entities: 1000000
      # interval is in seconds
      interval: 0
      last_run_state_db: person_locations.db
  - name: Crime cases
    type: crime_csv
    enabled: false
    settings:
      table:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      # injest only once
      interval: 0
      sample_file: ../samples/crime-cases.csv.gz
log:
  level: INFO
