sink:
  type: clickhouse
  addresses: 
    - 13.52.251.59:9000
  cred:
    type: basic_auth
    context:
      username: default
      password: admin
  context: 
settings:
  types:
    - metric
    - log 
  concurrency: 1
  batch_size: 1000
  # interval is in seconds
  interval: 5
  # backfill is in hours
  backfill: 24 
  # total emulated enties, hosts, devices etc
  total_entities: 100000

  # FIXME
  last_run_state_db: device_locations.db
  sample_log_file: clickhouse-server.log.gz
log:
  level: INFO