sink:
  type: clickhouse
  addresses: 
    - 13.52.251.59:9000
  cred:
    type: basic_auth
    context:
      username: default
      password: admin
  context: 
sources:
  - name: application log 
    type: log
    enabled: true
    settings:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      # interval is in seconds
      interval: 2
      sample_file: ../samples/clickhouse-server.log.gz
  - name: IoT device metric 
    type: metric 
    enabled: true
    settings:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      total_entities: 10000
      # interval is in seconds
      interval: 5
      last_run_state_db: device_locations.db
  - name: Crime cases 
    type: crime_csv
    enabled: true
    settings:
      clean_before_load: true
      concurrency: 1
      batch_size: 1000
      # injest only once
      interval: 0
      sample_file: ../samples/crime-cases.csv.gz
log:
  level: INFO